# Virtual Try-On Configuration File
# Edit these parameters for different runs

# Model Configuration
model:
  path: "franciszzj/Leffa"  # Path to Leffa model (local path or HuggingFace model)
  viton_type: "hd"          # Virtual try-on type: 'hd' for upper body, 'dc' for lower body
  device: "auto"            # Device: 'cuda', 'cpu', or 'auto'

# Inference Parameters
inference:
  steps: 20                 # Number of inference steps (10-50, higher = better quality but slower)
  cfg: 2.5                  # Classifier-free guidance scale (1.0-7.5, higher = more adherence to prompt)
  seed: null                # Random seed for reproducible results (null = random)

# Image Processing
processing:
  skip_pose: false          # Skip pose detection and use dummy pose (faster but lower quality)
  target_size: 768          # Target size for processing (768 or 1024)

# Input/Output Paths
paths:
  user_image: ""            # Path or URL to user/model image
  garment_image: ""         # Path or URL to garment/clothing image
  mask_image: ""            # Path or URL to mask image
  output: "output_tryon.png" # Output image path

# Predefined Mask URLs (for convenience)
mask_urls:
  upper: "https://storage.googleapis.com/mask_images/upper_mask.png"
  lower: "https://storage.googleapis.com/mask_images/lower_mask.png"
  full: "https://storage.googleapis.com/mask_images/upper_mask.png"

# Example Configurations
examples:
  # Upper body try-on (shirts, jackets, etc.)
  upper_body:
    viton_type: "hd"
    mask_image: "https://storage.googleapis.com/mask_images/upper_mask.png"
    steps: 20
    cfg: 2.5
  
  # Lower body try-on (pants, skirts, etc.)
  lower_body:
    viton_type: "dc"
    mask_image: "https://storage.googleapis.com/mask_images/lower_mask.png"
    steps: 25
    cfg: 3.0
  
  # High quality (slower but better results)
  high_quality:
    steps: 30
    cfg: 3.5
    skip_pose: false
  
  # Fast mode (faster but lower quality)
  fast_mode:
    steps: 15
    cfg: 2.0
    skip_pose: true

# Advanced Parameters (for fine-tuning)
advanced:
  # Memory optimization
  enable_memory_efficient_attention: true
  use_half_precision: false
  
  # Processing options
  resize_method: "lanczos"
  interpolation: "bilinear"
  
  # Pose detection settings
  pose_target_size: 512
  pose_include_hands: true
  pose_include_face: false
